#!/usr/bin/env bash
set -euo pipefail
set -x

echo "[runpod] Starting setup..."
date
pwd

if ! command -v uv >/dev/null 2>&1; then
  echo "[runpod] Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.cargo/bin:$PATH"
  uv --version || true
fi

if [ ! -d ".venv" ]; then
  echo "[runpod] Initializing uv venv..."
  uv venv
fi

PYTHON_BIN=".venv/bin/python"

echo "[runpod] Installing Python dependencies..."
uv pip install --python "$PYTHON_BIN" -r runpod_tools/requirements.txt
uv pip list --python "$PYTHON_BIN" | head -n 50 || true

echo "[runpod] Verifying GPU availability..."
nvidia-smi || true
nvidia-smi -L || true

EPOCHS="${EPOCHS:-5}"
MAX_STEPS="${MAX_STEPS:-0}"
LOGGING_STEPS="${LOGGING_STEPS:-5}"
SAVE_STEPS="${SAVE_STEPS:-50}"
WARMUP_STEPS="${WARMUP_STEPS:-0}"
WARMUP_RATIO="${WARMUP_RATIO:-0.03}"

echo "[runpod] Launching training..."
"$PYTHON_BIN" runpod_tools/train_qwen3_unsloth.py \
  --epochs "$EPOCHS" \
  --max-steps "$MAX_STEPS" \
  --logging-steps "$LOGGING_STEPS" \
  --save-steps "$SAVE_STEPS" \
  --warmup-steps "$WARMUP_STEPS" \
  --warmup-ratio "$WARMUP_RATIO" \
  --debug

# Arriving here, the model is saved in the directory selected/generated by the python script.
# if [[ "${MAKE_TAR:-1}" == "1" ]]; then
#   echo "[runpod] Creating model archive..."
#   # You can archive the output folder manually if needed
#   # tar -czf output.tar.gz output/
# fi
